language: node_js
node_js:
  - 7.10.0

branches:
  only:
  - master

addons:
  firefox: "latest"

before_install:
  - yarn global add @angular/cli

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - yarn install

script:
  - yarn run travis-test